name: CI
on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_call:

env:
  UV_VERSION: "0.9.15"

jobs:
  tests:
    name: Test on Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10", "3.11", "3.12", "3.13", "3.14" ]

    steps:
      - name: Checkout repository ${{ github.repository }}
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd  # v5

      - name: Setup uv and python
        uses: astral-sh/setup-uv@681c641aba71e4a1c380be3ab5e12ad51f415867  # v7
        with:
          enable-cache: true
          python-version: ${{ matrix.python-version }}
          version: ${{ env.UV_VERSION }}

      - name: Install dependencies
        run: uv sync --locked --all-extras --dev

      - name: Lint
        run: uv run ruff check

      - name: Check formatting
        run: uv run ruff format --diff

      - name: Run tests
        run: uv run pytest tests
